// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2dFmn3gi2uyBCuyceFXPWD3evX4VnDMU',
    appId: '1:316151000725:web:3ef32d5ed48cda1029359c',
    messagingSenderId: '316151000725',
    projectId: 'pi-control-5a4bd',
    authDomain: 'pi-control-5a4bd.firebaseapp.com',
    databaseURL: 'https://pi-control-5a4bd-default-rtdb.firebaseio.com',
    storageBucket: 'pi-control-5a4bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPAO86FUtzTLHFPJD_AI5LkCDgH6p_HL0',
    appId: '1:316151000725:android:09a149646873a5cf29359c',
    messagingSenderId: '316151000725',
    projectId: 'pi-control-5a4bd',
    databaseURL: 'https://pi-control-5a4bd-default-rtdb.firebaseio.com',
    storageBucket: 'pi-control-5a4bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYf65MuX-6bAnTMm8THj4YK88U0qNepV4',
    appId: '1:316151000725:ios:814b033a8d95abec29359c',
    messagingSenderId: '316151000725',
    projectId: 'pi-control-5a4bd',
    databaseURL: 'https://pi-control-5a4bd-default-rtdb.firebaseio.com',
    storageBucket: 'pi-control-5a4bd.firebasestorage.app',
    iosBundleId: 'com.example.accessControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYf65MuX-6bAnTMm8THj4YK88U0qNepV4',
    appId: '1:316151000725:ios:814b033a8d95abec29359c',
    messagingSenderId: '316151000725',
    projectId: 'pi-control-5a4bd',
    databaseURL: 'https://pi-control-5a4bd-default-rtdb.firebaseio.com',
    storageBucket: 'pi-control-5a4bd.firebasestorage.app',
    iosBundleId: 'com.example.accessControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2dFmn3gi2uyBCuyceFXPWD3evX4VnDMU',
    appId: '1:316151000725:web:b3060f92466a29f329359c',
    messagingSenderId: '316151000725',
    projectId: 'pi-control-5a4bd',
    authDomain: 'pi-control-5a4bd.firebaseapp.com',
    databaseURL: 'https://pi-control-5a4bd-default-rtdb.firebaseio.com',
    storageBucket: 'pi-control-5a4bd.firebasestorage.app',
  );
}
